"""many to many

Revision ID: c11d25254b95
Revises: e0f1a00b91a8
Create Date: 2024-02-15 17:07:55.779537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11d25254b95'
down_revision: Union[str, None] = 'e0f1a00b91a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_groups_id'), 'access_groups', ['id'], unique=False)
    op.create_index(op.f('ix_access_groups_name'), 'access_groups', ['name'], unique=True)
    op.create_table('user_access_groups',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('access_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['access_group_id'], ['access_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_column('files', 'access_level')
    op.drop_column('users', 'access_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_level', sa.INTEGER(), nullable=True))
    op.add_column('files', sa.Column('access_level', sa.INTEGER(), nullable=True))
    op.drop_table('user_access_groups')
    op.drop_index(op.f('ix_access_groups_name'), table_name='access_groups')
    op.drop_index(op.f('ix_access_groups_id'), table_name='access_groups')
    op.drop_table('access_groups')
    # ### end Alembic commands ###
